BEGIN TRANSACTION;
CREATE TABLE `kanjiTable` (
	`stt`	INTEGER NOT NULL,
	`mean`	TEXT,
	PRIMARY KEY(stt)
);
INSERT INTO `kanjiTable` (stt,mean) VALUES (1,'I, Me'),
 (2,'One'),
 (3,'Two'),
 (4,'Three'),
 (5,'Tree'),
 (6,'Gold, Money'),
 (7,'Circle'),
 (8,'Person'),
 (9,'Now');
CREATE TABLE "SampleTable" (
	`id`	INTEGER NOT NULL,
	`kanjiSTT`	INTEGER NOT NULL,
	`kanji`	TEXT,
	`romanji`	TEXT,
	`mean`	INTEGER,
	PRIMARY KEY(id,kanjiSTT)
);
INSERT INTO `SampleTable` (id,kanjiSTT,kanji,romanji,mean) VALUES (1,1,'私達','わたしたち
','we; us'),
 (2,1,'私宛','わたしあて','my address'),
 (3,1,'私自身','わたしじしん','myself'),
 (4,1,'私的','わたしてき','my style; my way; my opinion'),
 (5,1,'私語り','わたしがた','first-person narrative'),
 (6,1,'私も亦','わたしまた','me too; I also'),
 (7,2,'一つ','ひとつ','one thing'),
 (8,2,'一致','いっち','coincidence; agreement; union; match'),
 (9,2,'一番','いちばん','number one; first; first place'),
 (10,2,'一緒','いっしょ','together'),
 (11,2,'一昨年','いっさくねん','year before last'),
 (12,2,'一寸','ちょっと','just a minute;'),
 (13,3,'二十日','はつか','twentieth day of the month'),
 (14,3,'二日','ふつか','second day of the month'),
 (15,3,'二人','ふたり','two persons'),
 (16,3,'二十歳','はたち','20 years old'),
 (17,3,'二部','にぶ','two parts; two copies; the second part'),
 (18,3,'二番','にばん','second; number two; runner-up'),
 (19,4,'三日','みっか','the third day of the month'),
 (20,4,'三鞭酒','しゃんぺん','champagne'),
 (21,4,'三振','さんしん','strikeout; strike out; fanning out'),
 (22,4,'三枚','さんまい','three flat objects (e.g. tickets, pieces of cloth, etc.)'),
 (23,4,'三日月','みかずき','new moon; crescent moon'),
 (24,4,'三月','さんがつ','March'),
 (25,5,'木曜日','もくようび','Thursday'),
 (26,5,'木材','もくざい','lumber; timber; wood'),
 (27,5,'木綿','もめん','cotton (material)'),
 (28,5,'木星','もくせい','Jupiter (planet)'),
 (29,5,'植木','うえき','garden shrubs, trees, potted plant'),
 (30,5,'並木','なみき','roadside tree; row of trees'),
 (31,6,'金曜日','きんようび','Friday'),
 (32,6,'金融','きんゆう','financing; credit transacting; loaning of money; circulation of money'),
 (33,6,'金庫','きんこ','safe; strongbox; cashbox;'),
 (34,6,'奨学金','しょうがくきん','scholarship; stipend; bursary'),
 (35,6,'賃金','ちんぎん','wages'),
 (36,6,'預金','よきん','deposit; bank account'),
 (37,7,'円満','えんまん','perfection; harmony; peace;'),
 (38,7,'円柱','えんちゅう','column; shaft; cylinder'),
 (39,7,'円形','えんけい','round shape; circle'),
 (40,7,'楕円','だえん','ellipse'),
 (41,7,'億円','おくえん','100,000,000 yen'),
 (42,7,'魔法円','まほうえん','magic circle'),
 (43,8,'人形','にんぎょう','doll; puppet; figure'),
 (44,8,'人口','じんこう','population'),
 (45,8,'人文科学','じんぶんかがく','humanities; social sciences; liberal arts'),
 (46,8,'商人','しょうにん','trader; shopkeeper; merchant'),
 (47,8,'恋人','こいびと','lover; sweetheart'),
 (48,8,'殺人','さつじん','murder'),
 (49,9,'今年','ことし','this year'),
 (50,9,'今夏','こんか','this summer; next summer; last summer'),
 (51,9,'昨今','さっこん','nowadays; recently'),
 (52,9,'ただ今','ただいま','Here I am; I''m home!'),
 (53,9,'今にも','いまにも','at any time; soon'),
 (54,9,'今に','いま
に','before long; even now');
COMMIT;
